name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type 'destroy' to confirm"
        required: true

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files
    - name: Terraform Init
      working-directory: infra/app_infra
      run: terraform init -backend-config="bucket=${{ secrets.GCS_TF_BUCKET }}"
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

    # Generates an execution plan for Terraform
    - name: Terraform Destroy
      if: github.event.inputs.confirm_destroy == 'destroy'
      working-directory: infra/app_infra
      run: terraform destroy -auto-approve 
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        TF_VAR_gcs_tf_bucket: ${{ secrets.GCS_TF_BUCKET }}
        TF_VAR_project_id: ${{ secrets.PROJECT_ID }}